name: shop_task
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  bloc: ^9.1.0
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  http: ^1.6.0
  internet_connection_checker: ^3.0.1
  meta: ^1.17.0
  path: ^1.9.1
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
